### PR TITLE
ensures that com.co urls pass

### PR DESCRIPTION
**Pull request by tbuchok**
this should help us get through the specs with `com.co` domains.

let mek now what you think -- is my indenting off? bugging you or okay for this merge? let me know, happy to adjust.

### CODE REVIEW

**Comment by wankdanker** [comment]
Is `com.co` the only legitimate Colombian "tld"?

**Comment by tbuchok** [comment]
here's what my ["research"](http://en.wikipedia.org/wiki/.co) comes up with:
- .co
- .com.co
- .net.co
- .nom.co
- .org.co

i'll try to add a few quick specs for that. will try to have updated in 5 - 10.

**Comment by tbuchok** [comment]
updated at https://github.com/mailcharts/node-domain-name-parser/commit/1ce80c2f3627afb924e2e5ff7b17ee7a8b5fe064

**Comment by wankdanker** [comment]
Cool. Looking good. I'll merge this.

If we need more of these special cases in the future, I propose that we start keeping our own database of countries (in place of `country-code-lookup`) which would contain an array of valid SLDs for each country.

**Comment by wankdanker** [comment]
v1.2.0 is on npm.

Thank you for your work.

**Comment by tbuchok** [comment]
thanks, dan.

**Pull request merged**
